### ISSUE TITLE
_dbm error

### ISSUE THREAD

**Issue by pablococeres** [samwillis/tetra#11]
Hi, when I run the server or tetrabuild in python3.10.4 in windows 10 show me this error.
File "~\AppData\Local\Programs\Python\Python310\lib\dbm\ndbm.py", line 3, in <module>
    from _dbm import *
ModuleNotFoundError: No module named '_dbm'

Is not a problem of python, I uninstalled tetra an the server runs normally

**Comment by pablococeres** [comment]
When I install again Tetra it works...

**Comment by pablococeres** [comment]
Sorry, When I modify settings and urls the error start again. Any idea?

**Comment by samwillis** [comment]
Thanks for the report, I'm currently not near a Windows machine. Could you post the full stack trace?

Tetra doesn't use dbm directly and so not sure what's triggering the error.

**Comment by samwillis** [comment]
Actually just spotted the error (VS Code had inserted a "auto" import for dbm, despite Tetra not using it). Will have a patched version released later.

**Comment by samwillis** [comment]
I have just uploaded a fixed version (v0.0.4) to PyPI. Let me know how you get on, Windows is less well tested than Linux and macOS.
